### ISSUE TITLE
Delegator check box not fixed on Lead (javascript is ugly because Phil wrote it) Needs to be cleaned up.

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/keep#100]
- [ ] Keep is doing too much KERI backend should push out notification to tell when its finished.
- [ ] Keep is just dispatching actions based on notifications. The logic is in the KERI Rest API not in KEEP.

**Comment by janetgonzales** [comment]
Phil promises to write prettier javascript 🐮
