### ISSUE TITLE
"A" control updates

### ISSUE THREAD

**Issue by pfeairheller** [WebOfTrust/keep#211]
Add indicator of Authenticated status to icon
Add Authenticated status in popup, and ability to spot check if not auth'ed
Add OOBI copy button to "A" popup
Add AID copy button "A" popup.
Add "Jump to Contact" as popup from "A" popup

Fix ones that have bleed through from screen under popup

**Comment by shakedown-street** [comment]
Resolved by https://github.com/WebOfTrust/keep/pull/220
