### ISSUE TITLE
Autofill problem for chrome remembered passcodes

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/keep#85]

**Comment by shakedown-street** [comment]
I've googled around and tried a bunch of things here and there doesn't seem to be any way to disable the chrome password manager from popping up and asking you if you want to save your password.  And for some reason if I *do* save the passcode, even if I add `autocomplete="off"` to the passcode input it still autofills the password in the form.  I've even tried setting the input type to text and hiding it on submit and it doesn't seem to have any affect.  Not sure what else I can try here, it seems like google doesn't want you to be able to disable the password autofilling/saving.
